# Variables de Entorno Globales: Crea un workflow que defina una variable de entorno a nivel de workflow y la use en dos jobs distintos.

name: Ejercicio 1 - Variables de Entorno Globales

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "Hola desde Job 1"
    steps:
      - name: Imprimir variable de entorno en Job 1
        run: echo $GLOBAL_VAR

  job2:
    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "Hola desde Job 2"
    steps:
      - name: Imprimir variable de entorno en Job 2
        run: echo $GLOBAL_VAR
        